### ISSUE TITLE
Error: Cannot find module 'unzip'

### ISSUE THREAD

**Issue by stentotre** [KnutSv/generator-vp-craft#1]
stens-imac:craftgen sten$ yo vp-craft
module.js:338
    throw err;
          ^
Error: Cannot find module 'unzip'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sten/.nvm/versions/node/v0.12.7/lib/node_modules/generator-vp-craft/generators/app/index.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
stens-imac:craftgen sten$

**Comment by stentotre** [comment]
Tried installing unzip globally, but then:
stens-imac:craftgen sten$ yo vp-craft
module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sten/.nvm/versions/node/v0.12.7/lib/node_modules/generator-vp-craft/generators/app/index.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
stens-imac:craftgen sten$

**Comment by stentotre** [comment]
Installed the required modules globally, then ran yo vp-craft:

stens-imac:craftgen sten$ yo vp-craft

```
 _-----_     ╭──────────────────────────╮
|       |    │    Welcome to the ace    │
|--(o)--|    │    generator-vp-craft    │
```

   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /**_A**_\   /
     |  ~  |
   **'._**.'__
 ´   `|° ´ Y`

(!) #expandFiles() is deprecated. Use the glob module.
(!) #expand() is deprecated. Use the glob module.

I'm all done. Running npm install && bower install for you to install the required dependencies. If this fails, try running the command yourself.

Downloading craft ...
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /Users/sten/vvv/www/craftgen/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/Users/sten/vvv/www/craftgen/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sten/vvv/www/craftgen/npm-debug.log
bower ENOENT        No bower.json present
Minimee downloaded
Craft downloaded
   create /Users/sten/vvv/www/craftgen/craft/config/general.php
   create /Users/sten/vvv/www/craftgen/craft/templates/_layout.html
   create /Users/sten/vvv/www/craftgen/craft/templates/entry.html
   create /Users/sten/vvv/www/craftgen/craft/templates/entry/default.html
   create /Users/sten/vvv/www/craftgen/craft/templates/item.html
   create /Users/sten/vvv/www/craftgen/craft/templates/item/default.html
   create /Users/sten/vvv/www/craftgen/craft/templates/macros/img.html
   create /Users/sten/vvv/www/craftgen/craft/templates/matrix.html
   create /Users/sten/vvv/www/craftgen/craft/templates/matrix/default.html
   create /Users/sten/vvv/www/craftgen/craft/templates/partials/breadcrumbs.html
   create /Users/sten/vvv/www/craftgen/craft/templates/partials/footer.html
   create /Users/sten/vvv/www/craftgen/craft/templates/partials/last-changed.html
   create /Users/sten/vvv/www/craftgen/craft/translations/no.php
Files copied
stens-imac:craftgen sten$

**Comment by KnutSv** [comment]
Can't reproduce the errors locally, I have:
node 6.4.0
npm 3.10.3
yo 1.8.4

**Comment by dom-kelly** [comment]
Doesn't work for me either unfortunately.

node 6.9.1
npm 4.0.5
yo 1.8.5
